version: "3.8"
services:
  server:
    container_name: EngineeringChallenge_Server
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/__pycache__
    env_file:
      - ./server/.env
    environment:
      - PYTHONPATH=/usr/src/app
      - PYTHONDONTWRITEBYTECODE=1
    restart: unless-stopped

  client:
    container_name: EngineeringChallenge_Client
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    restart: unless-stopped
